// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.getComments
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::fm_atradio::CommentView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetComments<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// (min: 1, max: 100)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    pub station: S,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetCommentsOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub items: Vec<CommentView<S>>,
    pub total: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `fm.atradio.getComments` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetCommentsOutput<S>` for this endpoint.*/
pub struct GetCommentsResponse;
impl jacquard_common::xrpc::XrpcResp for GetCommentsResponse {
    const NSID: &'static str = "fm.atradio.getComments";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetCommentsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetComments<S> {
    const NSID: &'static str = "fm.atradio.getComments";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetCommentsResponse;
}

/** Endpoint marker for the `fm.atradio.getComments` query.

Path: `/xrpc/fm.atradio.getComments`. The request payload type is `GetComments<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetCommentsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetCommentsRequest {
    const PATH: &'static str = "/xrpc/fm.atradio.getComments";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetComments<S>;
    type Response = GetCommentsResponse;
}

pub mod get_comments_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Station;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Station = Unset;
    }
    ///State transition - sets the `station` field to Set
    pub struct SetStation<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStation<St> {}
    impl<St: State> State for SetStation<St> {
        type Station = Set<members::station>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `station` field
        pub struct station(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetCommentsBuilder<St: get_comments_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>, Option<S>),
    _type: PhantomData<fn() -> S>,
}

impl GetComments<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetCommentsBuilder<get_comments_state::Empty, DefaultStr> {
        GetCommentsBuilder::new()
    }
}

impl<S: BosStr> GetComments<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetCommentsBuilder<get_comments_state::Empty, S> {
        GetCommentsBuilder::builder()
    }
}

impl GetCommentsBuilder<get_comments_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetCommentsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetCommentsBuilder<get_comments_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetCommentsBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: get_comments_state::State, S: BosStr> GetCommentsBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: get_comments_state::State, S: BosStr> GetCommentsBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> GetCommentsBuilder<St, S>
where
    St: get_comments_state::State,
    St::Station: get_comments_state::IsUnset,
{
    /// Set the `station` field (required)
    pub fn station(
        mut self,
        value: impl Into<S>,
    ) -> GetCommentsBuilder<get_comments_state::SetStation<St>, S> {
        self._fields.2 = Option::Some(value.into());
        GetCommentsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetCommentsBuilder<St, S>
where
    St: get_comments_state::State,
    St::Station: get_comments_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetComments<S> {
        GetComments {
            cursor: self._fields.0,
            limit: self._fields.1,
            station: self._fields.2.unwrap(),
        }
    }
}
