// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.getListenerCounts
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::fm_atradio::ListenerCount;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetListenerCounts<S: BosStr = DefaultStr> {
    pub stations: S,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct GetListenerCountsOutput<S: BosStr = DefaultStr> {
    pub counts: Vec<ListenerCount<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `fm.atradio.getListenerCounts` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetListenerCountsOutput<S>` for this endpoint.*/
pub struct GetListenerCountsResponse;
impl jacquard_common::xrpc::XrpcResp for GetListenerCountsResponse {
    const NSID: &'static str = "fm.atradio.getListenerCounts";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetListenerCountsOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetListenerCounts<S> {
    const NSID: &'static str = "fm.atradio.getListenerCounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetListenerCountsResponse;
}

/** Endpoint marker for the `fm.atradio.getListenerCounts` query.

Path: `/xrpc/fm.atradio.getListenerCounts`. The request payload type is `GetListenerCounts<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetListenerCountsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetListenerCountsRequest {
    const PATH: &'static str = "/xrpc/fm.atradio.getListenerCounts";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetListenerCounts<S>;
    type Response = GetListenerCountsResponse;
}

pub mod get_listener_counts_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Stations;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Stations = Unset;
    }
    ///State transition - sets the `stations` field to Set
    pub struct SetStations<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStations<St> {}
    impl<St: State> State for SetStations<St> {
        type Stations = Set<members::stations>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `stations` field
        pub struct stations(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetListenerCountsBuilder<St: get_listener_counts_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>,),
    _type: PhantomData<fn() -> S>,
}

impl GetListenerCounts<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetListenerCountsBuilder<get_listener_counts_state::Empty, DefaultStr> {
        GetListenerCountsBuilder::new()
    }
}

impl<S: BosStr> GetListenerCounts<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetListenerCountsBuilder<get_listener_counts_state::Empty, S> {
        GetListenerCountsBuilder::builder()
    }
}

impl GetListenerCountsBuilder<get_listener_counts_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetListenerCountsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetListenerCountsBuilder<get_listener_counts_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetListenerCountsBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetListenerCountsBuilder<St, S>
where
    St: get_listener_counts_state::State,
    St::Stations: get_listener_counts_state::IsUnset,
{
    /// Set the `stations` field (required)
    pub fn stations(
        mut self,
        value: impl Into<S>,
    ) -> GetListenerCountsBuilder<get_listener_counts_state::SetStations<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetListenerCountsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetListenerCountsBuilder<St, S>
where
    St: get_listener_counts_state::State,
    St::Stations: get_listener_counts_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetListenerCounts<S> {
        GetListenerCounts {
            stations: self._fields.0.unwrap(),
        }
    }
}
