// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.updateSeen
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::string::Datetime;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct UpdateSeen<S: BosStr = DefaultStr> {
    ///DID or handle of the recipient.
    pub actor: AtIdentifier<S>,
    ///Time to mark seen up to (defaults to now).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seen_at: Option<Datetime>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct UpdateSeenOutput<S: BosStr = DefaultStr> {
    pub unread_count: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `fm.atradio.updateSeen` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `UpdateSeenOutput<S>` for this endpoint.*/
pub struct UpdateSeenResponse;
impl jacquard_common::xrpc::XrpcResp for UpdateSeenResponse {
    const NSID: &'static str = "fm.atradio.updateSeen";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = UpdateSeenOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for UpdateSeen<S> {
    const NSID: &'static str = "fm.atradio.updateSeen";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = UpdateSeenResponse;
}

/** Endpoint marker for the `fm.atradio.updateSeen` procedure.

Path: `/xrpc/fm.atradio.updateSeen`. The request payload type is `UpdateSeen<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct UpdateSeenRequest;
impl jacquard_common::xrpc::XrpcEndpoint for UpdateSeenRequest {
    const PATH: &'static str = "/xrpc/fm.atradio.updateSeen";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = UpdateSeen<S>;
    type Response = UpdateSeenResponse;
}

pub mod update_seen_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetActor<St> {}
    impl<St: State> State for SetActor<St> {
        type Actor = Set<members::actor>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
    }
}

/// Builder for constructing an instance of this type.
pub struct UpdateSeenBuilder<St: update_seen_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtIdentifier<S>>, Option<Datetime>),
    _type: PhantomData<fn() -> S>,
}

impl UpdateSeen<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> UpdateSeenBuilder<update_seen_state::Empty, DefaultStr> {
        UpdateSeenBuilder::new()
    }
}

impl<S: BosStr> UpdateSeen<S> {
    /// Create a new builder for this type
    pub fn builder() -> UpdateSeenBuilder<update_seen_state::Empty, S> {
        UpdateSeenBuilder::builder()
    }
}

impl UpdateSeenBuilder<update_seen_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        UpdateSeenBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> UpdateSeenBuilder<update_seen_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        UpdateSeenBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> UpdateSeenBuilder<St, S>
where
    St: update_seen_state::State,
    St::Actor: update_seen_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<AtIdentifier<S>>,
    ) -> UpdateSeenBuilder<update_seen_state::SetActor<St>, S> {
        self._fields.0 = Option::Some(value.into());
        UpdateSeenBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: update_seen_state::State, S: BosStr> UpdateSeenBuilder<St, S> {
    /// Set the `seenAt` field (optional)
    pub fn seen_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `seenAt` field to an Option value (optional)
    pub fn maybe_seen_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> UpdateSeenBuilder<St, S>
where
    St: update_seen_state::State,
    St::Actor: update_seen_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> UpdateSeen<S> {
        UpdateSeen {
            actor: self._fields.0.unwrap(),
            seen_at: self._fields.1,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> UpdateSeen<S> {
        UpdateSeen {
            actor: self._fields.0.unwrap(),
            seen_at: self._fields.1,
            extra_data: Some(extra_data),
        }
    }
}
