//! Generated `fm.atradio.*` lexicon bindings.
//!
//! **Scaffold:** empty for now. During the CLI migration the code generated by
//! `jacquard-lexgen` from `packages/lexicons/lexicons/atradio/*.json` moves here
//! verbatim (from `cli/src/fm_atradio/`), and `scripts/gen-lexicons.sh` is
//! repointed to regenerate into this directory. See `docs/sdk-design.md`.
//!
//! Once populated, this module holds the typed records (`Station`, `Favorite`,
//! `Comment`, `Reaction`, `actor::status::Status`, `audio::settings`), their
//! builders, and the shared `defs` view types — each implementing jacquard's
//! `Collection` so they plug straight into the agent's write path.
