

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_atradio_uniffi_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_atradio_uniffi_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_atradio_uniffi_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("atradio_uniffi")
    from . import _native as _atradio_native  # atradio: download-on-load
    path = _atradio_native.resolve()
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 26
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_atradio_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_atradio_uniffi_checksum_func_favorite_rkey() != 61027:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_comment() != 1587:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_delete_play_status() != 4959:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_did() != 65252:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_favorite() != 61695:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_refresh_session() != 28729:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_set_play_status() != 11876:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_agent_unfavorite() != 25902:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_appview_favorites() != 32795:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_appview_global_recently_played() != 27449:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_appview_popular_stations() != 60613:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_method_appview_recent_stations() != 15897:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_constructor_agent_login_password() != 59431:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_atradio_uniffi_checksum_constructor_appview_new() != 7781:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UniffiLib.uniffi_atradio_uniffi_fn_clone_agent.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_clone_agent.restype = ctypes.c_void_p
_UniffiLib.uniffi_atradio_uniffi_fn_free_agent.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_free_agent.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_constructor_agent_login_password.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_constructor_agent_login_password.restype = ctypes.c_void_p
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_comment.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_comment.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_delete_play_status.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_delete_play_status.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_did.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_did.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_favorite.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_favorite.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_refresh_session.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_refresh_session.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_set_play_status.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_set_play_status.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_unfavorite.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_unfavorite.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_clone_appview.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_clone_appview.restype = ctypes.c_void_p
_UniffiLib.uniffi_atradio_uniffi_fn_free_appview.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_free_appview.restype = None
_UniffiLib.uniffi_atradio_uniffi_fn_constructor_appview_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_constructor_appview_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_favorites.argtypes = (
    ctypes.c_void_p,
    _UniffiRustBuffer,
    ctypes.c_uint32,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_favorites.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_global_recently_played.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint32,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_global_recently_played.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_popular_stations.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint32,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_popular_stations.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_recent_stations.argtypes = (
    ctypes.c_void_p,
    ctypes.c_uint32,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_recent_stations.restype = _UniffiRustBuffer
_UniffiLib.uniffi_atradio_uniffi_fn_func_favorite_rkey.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_atradio_uniffi_fn_func_favorite_rkey.restype = _UniffiRustBuffer
_UniffiLib.ffi_atradio_uniffi_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_atradio_uniffi_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_atradio_uniffi_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rustbuffer_free.restype = None
_UniffiLib.ffi_atradio_uniffi_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i8.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i16.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_u64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_u64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_i64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_i64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_f32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_f32.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_f64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_f64.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_pointer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_poll_void.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_cancel_void.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_atradio_uniffi_rust_future_free_void.restype = None
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_atradio_uniffi_rust_future_complete_void.restype = None
_UniffiLib.uniffi_atradio_uniffi_checksum_func_favorite_rkey.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_func_favorite_rkey.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_comment.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_comment.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_delete_play_status.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_delete_play_status.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_did.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_did.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_favorite.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_favorite.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_refresh_session.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_refresh_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_set_play_status.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_set_play_status.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_unfavorite.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_agent_unfavorite.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_favorites.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_favorites.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_global_recently_played.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_global_recently_played.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_popular_stations.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_popular_stations.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_recent_stations.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_method_appview_recent_stations.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_constructor_agent_login_password.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_constructor_agent_login_password.restype = ctypes.c_uint16
_UniffiLib.uniffi_atradio_uniffi_checksum_constructor_appview_new.argtypes = (
)
_UniffiLib.uniffi_atradio_uniffi_checksum_constructor_appview_new.restype = ctypes.c_uint16
_UniffiLib.ffi_atradio_uniffi_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_atradio_uniffi_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.


class _UniffiConverterUInt32(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u32"
    VALUE_MIN = 0
    VALUE_MAX = 2**32

    @staticmethod
    def read(buf):
        return buf.read_u32()

    @staticmethod
    def write(value, buf):
        buf.write_u32(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



class AgentProtocol(typing.Protocol):
    """
    The atradio agent: app-password login + record writes.
    """

    def comment(self, station: "StationInfo",text: "str"):
        """
        Post a comment on a station. Returns the record URI.
        """

        raise NotImplementedError
    def delete_play_status(self, ):
        """
        Delete the actor's play-status singleton.
        """

        raise NotImplementedError
    def did(self, ):
        raise NotImplementedError
    def favorite(self, station: "StationInfo"):
        """
        Favorite a station (idempotent; deterministic record key). Returns URI.
        """

        raise NotImplementedError
    def refresh_session(self, ):
        """
        Proactively refresh the session (keep-alive).
        """

        raise NotImplementedError
    def set_play_status(self, station: "StationInfo"):
        """
        Update the actor's play-status singleton.
        """

        raise NotImplementedError
    def unfavorite(self, station: "StationInfo"):
        """
        Unfavorite a station (removes every record for its stationId).
        """

        raise NotImplementedError


class Agent:
    """
    The atradio agent: app-password login + record writes.
    """

    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_free_agent, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_clone_agent, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst
    @classmethod
    def login_password(cls, session_path: "str",identifier: "str",password: "str",appview: "typing.Optional[str]"):
        """
        Log in with an app password, persisting the session at `session_path`.
        """

        _UniffiConverterString.check_lower(session_path)
        
        _UniffiConverterString.check_lower(identifier)
        
        _UniffiConverterString.check_lower(password)
        
        _UniffiConverterOptionalString.check_lower(appview)
        
        # Call the (fallible) function before creating any half-baked object instances.
        pointer = _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_constructor_agent_login_password,
        _UniffiConverterString.lower(session_path),
        _UniffiConverterString.lower(identifier),
        _UniffiConverterString.lower(password),
        _UniffiConverterOptionalString.lower(appview))
        return cls._make_instance_(pointer)



    def comment(self, station: "StationInfo",text: "str") -> "str":
        """
        Post a comment on a station. Returns the record URI.
        """

        _UniffiConverterTypeStationInfo.check_lower(station)
        
        _UniffiConverterString.check_lower(text)
        
        return _UniffiConverterString.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_comment,self._uniffi_clone_pointer(),
        _UniffiConverterTypeStationInfo.lower(station),
        _UniffiConverterString.lower(text))
        )





    def delete_play_status(self, ) -> None:
        """
        Delete the actor's play-status singleton.
        """

        _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_delete_play_status,self._uniffi_clone_pointer(),)






    def did(self, ) -> "typing.Optional[str]":
        return _UniffiConverterOptionalString.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_did,self._uniffi_clone_pointer(),)
        )





    def favorite(self, station: "StationInfo") -> "str":
        """
        Favorite a station (idempotent; deterministic record key). Returns URI.
        """

        _UniffiConverterTypeStationInfo.check_lower(station)
        
        return _UniffiConverterString.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_favorite,self._uniffi_clone_pointer(),
        _UniffiConverterTypeStationInfo.lower(station))
        )





    def refresh_session(self, ) -> None:
        """
        Proactively refresh the session (keep-alive).
        """

        _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_refresh_session,self._uniffi_clone_pointer(),)






    def set_play_status(self, station: "StationInfo") -> None:
        """
        Update the actor's play-status singleton.
        """

        _UniffiConverterTypeStationInfo.check_lower(station)
        
        _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_set_play_status,self._uniffi_clone_pointer(),
        _UniffiConverterTypeStationInfo.lower(station))






    def unfavorite(self, station: "StationInfo") -> None:
        """
        Unfavorite a station (removes every record for its stationId).
        """

        _UniffiConverterTypeStationInfo.check_lower(station)
        
        _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_agent_unfavorite,self._uniffi_clone_pointer(),
        _UniffiConverterTypeStationInfo.lower(station))







class _UniffiConverterTypeAgent:

    @staticmethod
    def lift(value: int):
        return Agent._make_instance_(value)

    @staticmethod
    def check_lower(value: Agent):
        if not isinstance(value, Agent):
            raise TypeError("Expected Agent instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: AgentProtocol):
        if not isinstance(value, Agent):
            raise TypeError("Expected Agent instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: AgentProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))



class AppViewProtocol(typing.Protocol):
    """
    Unauthenticated read client over the public atradio.fm AppView.
    """

    def favorites(self, actor: "str",limit: "int"):
        raise NotImplementedError
    def global_recently_played(self, limit: "int"):
        raise NotImplementedError
    def popular_stations(self, limit: "int"):
        raise NotImplementedError
    def recent_stations(self, limit: "int"):
        raise NotImplementedError


class AppView:
    """
    Unauthenticated read client over the public atradio.fm AppView.
    """

    _pointer: ctypes.c_void_p
    def __init__(self, base: "typing.Optional[str]"):
        _UniffiConverterOptionalString.check_lower(base)
        
        self._pointer = _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_constructor_appview_new,
        _UniffiConverterOptionalString.lower(base))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_free_appview, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_clone_appview, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def favorites(self, actor: "str",limit: "int") -> "StationList":
        _UniffiConverterString.check_lower(actor)
        
        _UniffiConverterUInt32.check_lower(limit)
        
        return _UniffiConverterTypeStationList.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_favorites,self._uniffi_clone_pointer(),
        _UniffiConverterString.lower(actor),
        _UniffiConverterUInt32.lower(limit))
        )





    def global_recently_played(self, limit: "int") -> "typing.List[PlayView]":
        _UniffiConverterUInt32.check_lower(limit)
        
        return _UniffiConverterSequenceTypePlayView.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_global_recently_played,self._uniffi_clone_pointer(),
        _UniffiConverterUInt32.lower(limit))
        )





    def popular_stations(self, limit: "int") -> "typing.List[PopularItem]":
        _UniffiConverterUInt32.check_lower(limit)
        
        return _UniffiConverterSequenceTypePopularItem.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_popular_stations,self._uniffi_clone_pointer(),
        _UniffiConverterUInt32.lower(limit))
        )





    def recent_stations(self, limit: "int") -> "typing.List[StationView]":
        _UniffiConverterUInt32.check_lower(limit)
        
        return _UniffiConverterSequenceTypeStationView.lift(
            _uniffi_rust_call_with_error(_UniffiConverterTypeAtradioError,_UniffiLib.uniffi_atradio_uniffi_fn_method_appview_recent_stations,self._uniffi_clone_pointer(),
        _UniffiConverterUInt32.lower(limit))
        )






class _UniffiConverterTypeAppView:

    @staticmethod
    def lift(value: int):
        return AppView._make_instance_(value)

    @staticmethod
    def check_lower(value: AppView):
        if not isinstance(value, AppView):
            raise TypeError("Expected AppView instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: AppViewProtocol):
        if not isinstance(value, AppView):
            raise TypeError("Expected AppView instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: AppViewProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class ActorInfo:
    did: "str"
    handle: "typing.Optional[str]"
    display_name: "typing.Optional[str]"
    avatar: "typing.Optional[str]"
    def __init__(self, *, did: "str", handle: "typing.Optional[str]", display_name: "typing.Optional[str]", avatar: "typing.Optional[str]"):
        self.did = did
        self.handle = handle
        self.display_name = display_name
        self.avatar = avatar

    def __str__(self):
        return "ActorInfo(did={}, handle={}, display_name={}, avatar={})".format(self.did, self.handle, self.display_name, self.avatar)

    def __eq__(self, other):
        if self.did != other.did:
            return False
        if self.handle != other.handle:
            return False
        if self.display_name != other.display_name:
            return False
        if self.avatar != other.avatar:
            return False
        return True

class _UniffiConverterTypeActorInfo(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return ActorInfo(
            did=_UniffiConverterString.read(buf),
            handle=_UniffiConverterOptionalString.read(buf),
            display_name=_UniffiConverterOptionalString.read(buf),
            avatar=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.did)
        _UniffiConverterOptionalString.check_lower(value.handle)
        _UniffiConverterOptionalString.check_lower(value.display_name)
        _UniffiConverterOptionalString.check_lower(value.avatar)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.did, buf)
        _UniffiConverterOptionalString.write(value.handle, buf)
        _UniffiConverterOptionalString.write(value.display_name, buf)
        _UniffiConverterOptionalString.write(value.avatar, buf)


class PlayView:
    station: "StationInfo"
    played_at: "typing.Optional[str]"
    actor: "typing.Optional[ActorInfo]"
    def __init__(self, *, station: "StationInfo", played_at: "typing.Optional[str]", actor: "typing.Optional[ActorInfo]"):
        self.station = station
        self.played_at = played_at
        self.actor = actor

    def __str__(self):
        return "PlayView(station={}, played_at={}, actor={})".format(self.station, self.played_at, self.actor)

    def __eq__(self, other):
        if self.station != other.station:
            return False
        if self.played_at != other.played_at:
            return False
        if self.actor != other.actor:
            return False
        return True

class _UniffiConverterTypePlayView(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return PlayView(
            station=_UniffiConverterTypeStationInfo.read(buf),
            played_at=_UniffiConverterOptionalString.read(buf),
            actor=_UniffiConverterOptionalTypeActorInfo.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypeStationInfo.check_lower(value.station)
        _UniffiConverterOptionalString.check_lower(value.played_at)
        _UniffiConverterOptionalTypeActorInfo.check_lower(value.actor)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypeStationInfo.write(value.station, buf)
        _UniffiConverterOptionalString.write(value.played_at, buf)
        _UniffiConverterOptionalTypeActorInfo.write(value.actor, buf)


class PopularItem:
    station: "StationInfo"
    count: "int"
    def __init__(self, *, station: "StationInfo", count: "int"):
        self.station = station
        self.count = count

    def __str__(self):
        return "PopularItem(station={}, count={})".format(self.station, self.count)

    def __eq__(self, other):
        if self.station != other.station:
            return False
        if self.count != other.count:
            return False
        return True

class _UniffiConverterTypePopularItem(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return PopularItem(
            station=_UniffiConverterTypeStationInfo.read(buf),
            count=_UniffiConverterUInt32.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypeStationInfo.check_lower(value.station)
        _UniffiConverterUInt32.check_lower(value.count)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypeStationInfo.write(value.station, buf)
        _UniffiConverterUInt32.write(value.count, buf)


class StationInfo:
    """
    A self-contained station snapshot (`fm.atradio.defs#stationInfo`).
    """

    station_id: "str"
    name: "str"
    stream_url: "str"
    source: "str"
    description: "typing.Optional[str]"
    genre: "typing.Optional[str]"
    homepage: "typing.Optional[str]"
    logo: "typing.Optional[str]"
    country: "typing.Optional[str]"
    language: "typing.Optional[str]"
    bitrate: "typing.Optional[int]"
    codec: "typing.Optional[str]"
    tags: "typing.List[str]"
    def __init__(self, *, station_id: "str", name: "str", stream_url: "str", source: "str", description: "typing.Optional[str]", genre: "typing.Optional[str]", homepage: "typing.Optional[str]", logo: "typing.Optional[str]", country: "typing.Optional[str]", language: "typing.Optional[str]", bitrate: "typing.Optional[int]", codec: "typing.Optional[str]", tags: "typing.List[str]"):
        self.station_id = station_id
        self.name = name
        self.stream_url = stream_url
        self.source = source
        self.description = description
        self.genre = genre
        self.homepage = homepage
        self.logo = logo
        self.country = country
        self.language = language
        self.bitrate = bitrate
        self.codec = codec
        self.tags = tags

    def __str__(self):
        return "StationInfo(station_id={}, name={}, stream_url={}, source={}, description={}, genre={}, homepage={}, logo={}, country={}, language={}, bitrate={}, codec={}, tags={})".format(self.station_id, self.name, self.stream_url, self.source, self.description, self.genre, self.homepage, self.logo, self.country, self.language, self.bitrate, self.codec, self.tags)

    def __eq__(self, other):
        if self.station_id != other.station_id:
            return False
        if self.name != other.name:
            return False
        if self.stream_url != other.stream_url:
            return False
        if self.source != other.source:
            return False
        if self.description != other.description:
            return False
        if self.genre != other.genre:
            return False
        if self.homepage != other.homepage:
            return False
        if self.logo != other.logo:
            return False
        if self.country != other.country:
            return False
        if self.language != other.language:
            return False
        if self.bitrate != other.bitrate:
            return False
        if self.codec != other.codec:
            return False
        if self.tags != other.tags:
            return False
        return True

class _UniffiConverterTypeStationInfo(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StationInfo(
            station_id=_UniffiConverterString.read(buf),
            name=_UniffiConverterString.read(buf),
            stream_url=_UniffiConverterString.read(buf),
            source=_UniffiConverterString.read(buf),
            description=_UniffiConverterOptionalString.read(buf),
            genre=_UniffiConverterOptionalString.read(buf),
            homepage=_UniffiConverterOptionalString.read(buf),
            logo=_UniffiConverterOptionalString.read(buf),
            country=_UniffiConverterOptionalString.read(buf),
            language=_UniffiConverterOptionalString.read(buf),
            bitrate=_UniffiConverterOptionalUInt32.read(buf),
            codec=_UniffiConverterOptionalString.read(buf),
            tags=_UniffiConverterSequenceString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.station_id)
        _UniffiConverterString.check_lower(value.name)
        _UniffiConverterString.check_lower(value.stream_url)
        _UniffiConverterString.check_lower(value.source)
        _UniffiConverterOptionalString.check_lower(value.description)
        _UniffiConverterOptionalString.check_lower(value.genre)
        _UniffiConverterOptionalString.check_lower(value.homepage)
        _UniffiConverterOptionalString.check_lower(value.logo)
        _UniffiConverterOptionalString.check_lower(value.country)
        _UniffiConverterOptionalString.check_lower(value.language)
        _UniffiConverterOptionalUInt32.check_lower(value.bitrate)
        _UniffiConverterOptionalString.check_lower(value.codec)
        _UniffiConverterSequenceString.check_lower(value.tags)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.station_id, buf)
        _UniffiConverterString.write(value.name, buf)
        _UniffiConverterString.write(value.stream_url, buf)
        _UniffiConverterString.write(value.source, buf)
        _UniffiConverterOptionalString.write(value.description, buf)
        _UniffiConverterOptionalString.write(value.genre, buf)
        _UniffiConverterOptionalString.write(value.homepage, buf)
        _UniffiConverterOptionalString.write(value.logo, buf)
        _UniffiConverterOptionalString.write(value.country, buf)
        _UniffiConverterOptionalString.write(value.language, buf)
        _UniffiConverterOptionalUInt32.write(value.bitrate, buf)
        _UniffiConverterOptionalString.write(value.codec, buf)
        _UniffiConverterSequenceString.write(value.tags, buf)


class StationList:
    cursor: "typing.Optional[str]"
    total: "int"
    items: "typing.List[StationView]"
    def __init__(self, *, cursor: "typing.Optional[str]", total: "int", items: "typing.List[StationView]"):
        self.cursor = cursor
        self.total = total
        self.items = items

    def __str__(self):
        return "StationList(cursor={}, total={}, items={})".format(self.cursor, self.total, self.items)

    def __eq__(self, other):
        if self.cursor != other.cursor:
            return False
        if self.total != other.total:
            return False
        if self.items != other.items:
            return False
        return True

class _UniffiConverterTypeStationList(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StationList(
            cursor=_UniffiConverterOptionalString.read(buf),
            total=_UniffiConverterUInt32.read(buf),
            items=_UniffiConverterSequenceTypeStationView.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterOptionalString.check_lower(value.cursor)
        _UniffiConverterUInt32.check_lower(value.total)
        _UniffiConverterSequenceTypeStationView.check_lower(value.items)

    @staticmethod
    def write(value, buf):
        _UniffiConverterOptionalString.write(value.cursor, buf)
        _UniffiConverterUInt32.write(value.total, buf)
        _UniffiConverterSequenceTypeStationView.write(value.items, buf)


class StationView:
    uri: "str"
    station: "StationInfo"
    created_at: "typing.Optional[str]"
    def __init__(self, *, uri: "str", station: "StationInfo", created_at: "typing.Optional[str]"):
        self.uri = uri
        self.station = station
        self.created_at = created_at

    def __str__(self):
        return "StationView(uri={}, station={}, created_at={})".format(self.uri, self.station, self.created_at)

    def __eq__(self, other):
        if self.uri != other.uri:
            return False
        if self.station != other.station:
            return False
        if self.created_at != other.created_at:
            return False
        return True

class _UniffiConverterTypeStationView(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StationView(
            uri=_UniffiConverterString.read(buf),
            station=_UniffiConverterTypeStationInfo.read(buf),
            created_at=_UniffiConverterOptionalString.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.uri)
        _UniffiConverterTypeStationInfo.check_lower(value.station)
        _UniffiConverterOptionalString.check_lower(value.created_at)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.uri, buf)
        _UniffiConverterTypeStationInfo.write(value.station, buf)
        _UniffiConverterOptionalString.write(value.created_at, buf)


# AtradioError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class AtradioError(Exception):
    """
    Errors surfaced to host languages (one flat message; the SDK's typed errors
    are stringified at the boundary).
    """

    pass

_UniffiTempAtradioError = AtradioError

class AtradioError:  # type: ignore
    """
    Errors surfaced to host languages (one flat message; the SDK's typed errors
    are stringified at the boundary).
    """

    class Generic(_UniffiTempAtradioError):
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "AtradioError.Generic({})".format(str(self))
    _UniffiTempAtradioError.Generic = Generic # type: ignore

AtradioError = _UniffiTempAtradioError # type: ignore
del _UniffiTempAtradioError


class _UniffiConverterTypeAtradioError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return AtradioError.Generic(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, AtradioError.Generic):
            _UniffiConverterString.check_lower(value.message)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, AtradioError.Generic):
            buf.write_i32(1)
            _UniffiConverterString.write(value.message, buf)



class _UniffiConverterOptionalUInt32(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterUInt32.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterUInt32.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterUInt32.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeActorInfo(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeActorInfo.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeActorInfo.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeActorInfo.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterString.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypePlayView(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypePlayView.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypePlayView.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypePlayView.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypePopularItem(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypePopularItem.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypePopularItem.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypePopularItem.read(buf) for i in range(count)
        ]



class _UniffiConverterSequenceTypeStationView(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterTypeStationView.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterTypeStationView.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterTypeStationView.read(buf) for i in range(count)
        ]

# Async support

def favorite_rkey(station_id: "str") -> "str":
    """
    The deterministic favorite record key for a station id — identical across all
    atradio SDKs (Rust core, Go, TypeScript, and every FFI language).
    """

    _UniffiConverterString.check_lower(station_id)
    
    return _UniffiConverterString.lift(_uniffi_rust_call(_UniffiLib.uniffi_atradio_uniffi_fn_func_favorite_rkey,
        _UniffiConverterString.lower(station_id)))


__all__ = [
    "InternalError",
    "AtradioError",
    "ActorInfo",
    "PlayView",
    "PopularItem",
    "StationInfo",
    "StationList",
    "StationView",
    "favorite_rkey",
    "Agent",
    "AppView",
]

