// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.audio.settings
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// The actor's audio playback settings (10-band EQ + Rockbox DSP chain), a singleton record synced across devices. Gains are integers; the crossfeed direct gain is in tenths of dB, matching the Rockbox convention.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.audio.settings",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Settings<S: BosStr = DefaultStr> {
    ///Bass tone control in dB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bass: Option<i64>,
    ///Channel mixing mode.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel_mode: Option<SettingsChannelMode<S>>,
    ///Compressor ratio (n:1).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comp_ratio: Option<i64>,
    ///Compressor threshold in dB (0 = off).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comp_threshold: Option<i64>,
    ///Crossfeed direct-path gain in tenths of dB (<= 0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crossfeed_direct: Option<i64>,
    ///Headphone crossfeed mode.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crossfeed_mode: Option<SettingsCrossfeedMode<S>>,
    ///Whether the 10-band parametric EQ is enabled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eq_enabled: Option<bool>,
    ///Per-band EQ gain in dB, one entry per band (60 Hz - 20 kHz).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub eq_gains: Option<Vec<i64>>,
    ///Perceptual Bass Enhancement strength in percent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pbe: Option<i64>,
    ///PBE pre-cut in dB (stored positive, applied as a cut).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pbe_precut: Option<i64>,
    ///Stereo width in percent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stereo_width: Option<i64>,
    ///Haas surround balance in percent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub surround_balance: Option<i64>,
    ///Haas surround delay in ms (0 = off).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub surround_delay: Option<i64>,
    ///Treble tone control in dB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub treble: Option<i64>,
    pub updated_at: Datetime,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Channel mixing mode.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SettingsChannelMode<S: BosStr = DefaultStr> {
    Stereo,
    Mono,
    Custom,
    MonoLeft,
    MonoRight,
    Karaoke,
    Swap,
    Other(S),
}

impl<S: BosStr> SettingsChannelMode<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Stereo => "stereo",
            Self::Mono => "mono",
            Self::Custom => "custom",
            Self::MonoLeft => "mono-left",
            Self::MonoRight => "mono-right",
            Self::Karaoke => "karaoke",
            Self::Swap => "swap",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "stereo" => Self::Stereo,
            "mono" => Self::Mono,
            "custom" => Self::Custom,
            "mono-left" => Self::MonoLeft,
            "mono-right" => Self::MonoRight,
            "karaoke" => Self::Karaoke,
            "swap" => Self::Swap,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for SettingsChannelMode<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for SettingsChannelMode<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for SettingsChannelMode<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for SettingsChannelMode<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for SettingsChannelMode<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for SettingsChannelMode<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = SettingsChannelMode<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            SettingsChannelMode::Stereo => SettingsChannelMode::Stereo,
            SettingsChannelMode::Mono => SettingsChannelMode::Mono,
            SettingsChannelMode::Custom => SettingsChannelMode::Custom,
            SettingsChannelMode::MonoLeft => SettingsChannelMode::MonoLeft,
            SettingsChannelMode::MonoRight => SettingsChannelMode::MonoRight,
            SettingsChannelMode::Karaoke => SettingsChannelMode::Karaoke,
            SettingsChannelMode::Swap => SettingsChannelMode::Swap,
            SettingsChannelMode::Other(v) => SettingsChannelMode::Other(v.into_static()),
        }
    }
}

/// Headphone crossfeed mode.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SettingsCrossfeedMode<S: BosStr = DefaultStr> {
    Off,
    Meier,
    Custom,
    Other(S),
}

impl<S: BosStr> SettingsCrossfeedMode<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Off => "off",
            Self::Meier => "meier",
            Self::Custom => "custom",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "off" => Self::Off,
            "meier" => Self::Meier,
            "custom" => Self::Custom,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for SettingsCrossfeedMode<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for SettingsCrossfeedMode<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for SettingsCrossfeedMode<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for SettingsCrossfeedMode<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for SettingsCrossfeedMode<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for SettingsCrossfeedMode<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = SettingsCrossfeedMode<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            SettingsCrossfeedMode::Off => SettingsCrossfeedMode::Off,
            SettingsCrossfeedMode::Meier => SettingsCrossfeedMode::Meier,
            SettingsCrossfeedMode::Custom => SettingsCrossfeedMode::Custom,
            SettingsCrossfeedMode::Other(v) => {
                SettingsCrossfeedMode::Other(v.into_static())
            }
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct SettingsGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Settings<S>,
}

impl<S: BosStr> Settings<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, SettingsRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct SettingsRecord;
impl XrpcResp for SettingsRecord {
    const NSID: &'static str = "fm.atradio.audio.settings";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = SettingsGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<SettingsGetRecordOutput<S>> for Settings<S> {
    fn from(output: SettingsGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Settings<S> {
    const NSID: &'static str = "fm.atradio.audio.settings";
    type Record = SettingsRecord;
}

impl Collection for SettingsRecord {
    const NSID: &'static str = "fm.atradio.audio.settings";
    type Record = SettingsRecord;
}

impl<S: BosStr> LexiconSchema for Settings<S> {
    fn nsid() -> &'static str {
        "fm.atradio.audio.settings"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_audio_settings()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.bass {
            if *value > 24i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("bass"),
                    max: 24i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.bass {
            if *value < -24i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("bass"),
                    min: -24i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.comp_ratio {
            if *value > 10i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("comp_ratio"),
                    max: 10i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.comp_ratio {
            if *value < 2i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("comp_ratio"),
                    min: 2i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.comp_threshold {
            if *value > 0i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("comp_threshold"),
                    max: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.comp_threshold {
            if *value < -30i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("comp_threshold"),
                    min: -30i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.crossfeed_direct {
            if *value > 0i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("crossfeed_direct"),
                    max: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.crossfeed_direct {
            if *value < -60i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("crossfeed_direct"),
                    min: -60i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.pbe {
            if *value > 100i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("pbe"),
                    max: 100i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.pbe {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("pbe"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.pbe_precut {
            if *value > 24i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("pbe_precut"),
                    max: 24i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.pbe_precut {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("pbe_precut"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.stereo_width {
            if *value > 255i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("stereo_width"),
                    max: 255i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.stereo_width {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("stereo_width"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.surround_balance {
            if *value > 100i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("surround_balance"),
                    max: 100i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.surround_balance {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("surround_balance"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.surround_delay {
            if *value > 30i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("surround_delay"),
                    max: 30i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.surround_delay {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("surround_delay"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.treble {
            if *value > 24i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("treble"),
                    max: 24i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.treble {
            if *value < -24i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("treble"),
                    min: -24i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod settings_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type UpdatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type UpdatedAt = Unset;
    }
    ///State transition - sets the `updated_at` field to Set
    pub struct SetUpdatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUpdatedAt<St> {}
    impl<St: State> State for SetUpdatedAt<St> {
        type UpdatedAt = Set<members::updated_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `updated_at` field
        pub struct updated_at(());
    }
}

/// Builder for constructing an instance of this type.
pub struct SettingsBuilder<St: settings_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<i64>,
        Option<SettingsChannelMode<S>>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<SettingsCrossfeedMode<S>>,
        Option<bool>,
        Option<Vec<i64>>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<Datetime>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Settings<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> SettingsBuilder<settings_state::Empty, DefaultStr> {
        SettingsBuilder::new()
    }
}

impl<S: BosStr> Settings<S> {
    /// Create a new builder for this type
    pub fn builder() -> SettingsBuilder<settings_state::Empty, S> {
        SettingsBuilder::builder()
    }
}

impl SettingsBuilder<settings_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        SettingsBuilder {
            _state: PhantomData,
            _fields: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> SettingsBuilder<settings_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        SettingsBuilder {
            _state: PhantomData,
            _fields: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _type: PhantomData,
        }
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `bass` field (optional)
    pub fn bass(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `bass` field to an Option value (optional)
    pub fn maybe_bass(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `channelMode` field (optional)
    pub fn channel_mode(
        mut self,
        value: impl Into<Option<SettingsChannelMode<S>>>,
    ) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `channelMode` field to an Option value (optional)
    pub fn maybe_channel_mode(mut self, value: Option<SettingsChannelMode<S>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `compRatio` field (optional)
    pub fn comp_ratio(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `compRatio` field to an Option value (optional)
    pub fn maybe_comp_ratio(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `compThreshold` field (optional)
    pub fn comp_threshold(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `compThreshold` field to an Option value (optional)
    pub fn maybe_comp_threshold(mut self, value: Option<i64>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `crossfeedDirect` field (optional)
    pub fn crossfeed_direct(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `crossfeedDirect` field to an Option value (optional)
    pub fn maybe_crossfeed_direct(mut self, value: Option<i64>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `crossfeedMode` field (optional)
    pub fn crossfeed_mode(
        mut self,
        value: impl Into<Option<SettingsCrossfeedMode<S>>>,
    ) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `crossfeedMode` field to an Option value (optional)
    pub fn maybe_crossfeed_mode(
        mut self,
        value: Option<SettingsCrossfeedMode<S>>,
    ) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `eqEnabled` field (optional)
    pub fn eq_enabled(mut self, value: impl Into<Option<bool>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `eqEnabled` field to an Option value (optional)
    pub fn maybe_eq_enabled(mut self, value: Option<bool>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `eqGains` field (optional)
    pub fn eq_gains(mut self, value: impl Into<Option<Vec<i64>>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `eqGains` field to an Option value (optional)
    pub fn maybe_eq_gains(mut self, value: Option<Vec<i64>>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `pbe` field (optional)
    pub fn pbe(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `pbe` field to an Option value (optional)
    pub fn maybe_pbe(mut self, value: Option<i64>) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `pbePrecut` field (optional)
    pub fn pbe_precut(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.9 = value.into();
        self
    }
    /// Set the `pbePrecut` field to an Option value (optional)
    pub fn maybe_pbe_precut(mut self, value: Option<i64>) -> Self {
        self._fields.9 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `stereoWidth` field (optional)
    pub fn stereo_width(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.10 = value.into();
        self
    }
    /// Set the `stereoWidth` field to an Option value (optional)
    pub fn maybe_stereo_width(mut self, value: Option<i64>) -> Self {
        self._fields.10 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `surroundBalance` field (optional)
    pub fn surround_balance(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.11 = value.into();
        self
    }
    /// Set the `surroundBalance` field to an Option value (optional)
    pub fn maybe_surround_balance(mut self, value: Option<i64>) -> Self {
        self._fields.11 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `surroundDelay` field (optional)
    pub fn surround_delay(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.12 = value.into();
        self
    }
    /// Set the `surroundDelay` field to an Option value (optional)
    pub fn maybe_surround_delay(mut self, value: Option<i64>) -> Self {
        self._fields.12 = value;
        self
    }
}

impl<St: settings_state::State, S: BosStr> SettingsBuilder<St, S> {
    /// Set the `treble` field (optional)
    pub fn treble(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.13 = value.into();
        self
    }
    /// Set the `treble` field to an Option value (optional)
    pub fn maybe_treble(mut self, value: Option<i64>) -> Self {
        self._fields.13 = value;
        self
    }
}

impl<St, S: BosStr> SettingsBuilder<St, S>
where
    St: settings_state::State,
    St::UpdatedAt: settings_state::IsUnset,
{
    /// Set the `updatedAt` field (required)
    pub fn updated_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> SettingsBuilder<settings_state::SetUpdatedAt<St>, S> {
        self._fields.14 = Option::Some(value.into());
        SettingsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> SettingsBuilder<St, S>
where
    St: settings_state::State,
    St::UpdatedAt: settings_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Settings<S> {
        Settings {
            bass: self._fields.0,
            channel_mode: self._fields.1,
            comp_ratio: self._fields.2,
            comp_threshold: self._fields.3,
            crossfeed_direct: self._fields.4,
            crossfeed_mode: self._fields.5,
            eq_enabled: self._fields.6,
            eq_gains: self._fields.7,
            pbe: self._fields.8,
            pbe_precut: self._fields.9,
            stereo_width: self._fields.10,
            surround_balance: self._fields.11,
            surround_delay: self._fields.12,
            treble: self._fields.13,
            updated_at: self._fields.14.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Settings<S> {
        Settings {
            bass: self._fields.0,
            channel_mode: self._fields.1,
            comp_ratio: self._fields.2,
            comp_threshold: self._fields.3,
            crossfeed_direct: self._fields.4,
            crossfeed_mode: self._fields.5,
            eq_enabled: self._fields.6,
            eq_gains: self._fields.7,
            pbe: self._fields.8,
            pbe_precut: self._fields.9,
            stereo_width: self._fields.10,
            surround_balance: self._fields.11,
            surround_delay: self._fields.12,
            treble: self._fields.13,
            updated_at: self._fields.14.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_audio_settings() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.audio.settings"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "The actor's audio playback settings (10-band EQ + Rockbox DSP chain), a singleton record synced across devices. Gains are integers; the crossfeed direct gain is in tenths of dB, matching the Rockbox convention.",
                        ),
                    ),
                    key: Some(CowStr::new_static("literal:self")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(vec![SmolStr::new_static("updatedAt")]),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("bass"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(-24i64),
                                    maximum: Some(24i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("channelMode"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Channel mixing mode."),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("compRatio"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(2i64),
                                    maximum: Some(10i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("compThreshold"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(-30i64),
                                    maximum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("crossfeedDirect"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(-60i64),
                                    maximum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("crossfeedMode"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Headphone crossfeed mode."),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("eqEnabled"),
                                LexObjectProperty::Boolean(LexBoolean {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("eqGains"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Per-band EQ gain in dB, one entry per band (60 Hz - 20 kHz).",
                                        ),
                                    ),
                                    items: LexArrayItem::Integer(LexInteger {
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("pbe"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(100i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("pbePrecut"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(24i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("stereoWidth"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(255i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("surroundBalance"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(100i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("surroundDelay"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(30i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("treble"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(-24i64),
                                    maximum: Some(24i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("updatedAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}