// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.actor.status
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::fm_atradio::StationInfo;
/// The actor's current listening status: the station they most recently played and when. A singleton record, overwritten on each play.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.actor.status",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Status<S: BosStr = DefaultStr> {
    pub played_at: Datetime,
    pub station: StationInfo<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct StatusGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Status<S>,
}

impl<S: BosStr> Status<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, StatusRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct StatusRecord;
impl XrpcResp for StatusRecord {
    const NSID: &'static str = "fm.atradio.actor.status";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = StatusGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<StatusGetRecordOutput<S>> for Status<S> {
    fn from(output: StatusGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Status<S> {
    const NSID: &'static str = "fm.atradio.actor.status";
    type Record = StatusRecord;
}

impl Collection for StatusRecord {
    const NSID: &'static str = "fm.atradio.actor.status";
    type Record = StatusRecord;
}

impl<S: BosStr> LexiconSchema for Status<S> {
    fn nsid() -> &'static str {
        "fm.atradio.actor.status"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_actor_status()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

pub mod status_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type PlayedAt;
        type Station;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type PlayedAt = Unset;
        type Station = Unset;
    }
    ///State transition - sets the `played_at` field to Set
    pub struct SetPlayedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetPlayedAt<St> {}
    impl<St: State> State for SetPlayedAt<St> {
        type PlayedAt = Set<members::played_at>;
        type Station = St::Station;
    }
    ///State transition - sets the `station` field to Set
    pub struct SetStation<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStation<St> {}
    impl<St: State> State for SetStation<St> {
        type PlayedAt = St::PlayedAt;
        type Station = Set<members::station>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `played_at` field
        pub struct played_at(());
        ///Marker type for the `station` field
        pub struct station(());
    }
}

/// Builder for constructing an instance of this type.
pub struct StatusBuilder<St: status_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Datetime>, Option<StationInfo<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Status<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> StatusBuilder<status_state::Empty, DefaultStr> {
        StatusBuilder::new()
    }
}

impl<S: BosStr> Status<S> {
    /// Create a new builder for this type
    pub fn builder() -> StatusBuilder<status_state::Empty, S> {
        StatusBuilder::builder()
    }
}

impl StatusBuilder<status_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        StatusBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> StatusBuilder<status_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        StatusBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> StatusBuilder<St, S>
where
    St: status_state::State,
    St::PlayedAt: status_state::IsUnset,
{
    /// Set the `playedAt` field (required)
    pub fn played_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> StatusBuilder<status_state::SetPlayedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        StatusBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> StatusBuilder<St, S>
where
    St: status_state::State,
    St::Station: status_state::IsUnset,
{
    /// Set the `station` field (required)
    pub fn station(
        mut self,
        value: impl Into<StationInfo<S>>,
    ) -> StatusBuilder<status_state::SetStation<St>, S> {
        self._fields.1 = Option::Some(value.into());
        StatusBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> StatusBuilder<St, S>
where
    St: status_state::State,
    St::PlayedAt: status_state::IsSet,
    St::Station: status_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Status<S> {
        Status {
            played_at: self._fields.0.unwrap(),
            station: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Status<S> {
        Status {
            played_at: self._fields.0.unwrap(),
            station: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_actor_status() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.actor.status"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "The actor's current listening status: the station they most recently played and when. A singleton record, overwritten on each play.",
                        ),
                    ),
                    key: Some(CowStr::new_static("literal:self")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("station"),
                                SmolStr::new_static("playedAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("playedAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("station"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("fm.atradio.defs#stationInfo"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}