#!/usr/bin/env bash
# Regenerate sdk/erlang/priv/atradio_nif.manifest with a sha256 checksum for
# each per-triple NIF (`atradio_nif-<triple>.so`) in DIR — the release artifacts.
# The Erlang loader verifies its first-load download against these checksums.
#
# Usage: ./gen-erlang-manifest.sh <dir-of-so> <tag>
#   REPO=owner/repo  (default tsirysndr/atradio.fm)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
manifest="$here/../erlang/priv/atradio_nif.manifest"
dir="${1:?usage: gen-erlang-manifest.sh <dir-of-so> <tag>}"
tag="${2:?tag required, e.g. erlang-v0.1.0}"
repo="${REPO:-tsirysndr/atradio.fm}"

sha256() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

{
  echo "%% Generated by sdk/scripts/gen-erlang-manifest.sh — do not edit by hand."
  echo "{repo, \"$repo\"}."
  echo "{tag, \"$tag\"}."
  found=0
  for so in "$dir"/atradio_nif-*.so; do
    [ -e "$so" ] || continue
    found=1
    triple="$(basename "$so" .so)"; triple="${triple#atradio_nif-}"
    echo "{checksum, \"$triple\", \"$(sha256 "$so")\"}."
  done
  [ "$found" = 1 ] || { echo "no atradio_nif-*.so files in $dir" >&2; exit 1; }
} > "$manifest"

echo "wrote $manifest:"
cat "$manifest"
