// This file is @generated by prost-build.
/// The minimal station exchanged over the wire (mirrors remote::StationLite).
/// `id` uses the atradio convention: "rb:<uuid>" | "tunein:<id>" | "custom:<rkey>".
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Station {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub favicon: ::prost::alloc::string::String,
}
/// The Rockbox DSP chain (mirrors player::dsp::AudioSettings). Gains are dB.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioSettings {
    #[prost(bool, tag = "1")]
    pub eq_enabled: bool,
    /// Per-band gain in dB, one per band (32 Hz … 16 kHz), 10 entries.
    #[prost(int32, repeated, tag = "2")]
    pub eq_gains: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub bass: i32,
    #[prost(int32, tag = "4")]
    pub treble: i32,
    /// "off" | "meier" | "custom".
    #[prost(string, tag = "5")]
    pub crossfeed_mode: ::prost::alloc::string::String,
    /// Crossfeed direct-path gain in tenths of dB (<= 0).
    #[prost(int32, tag = "6")]
    pub crossfeed_direct_tenths: i32,
    #[prost(int32, tag = "7")]
    pub pbe: i32,
    #[prost(int32, tag = "8")]
    pub pbe_precut: i32,
    #[prost(int32, tag = "9")]
    pub surround_delay: i32,
    #[prost(int32, tag = "10")]
    pub surround_balance: i32,
    #[prost(int32, tag = "11")]
    pub comp_threshold: i32,
    #[prost(int32, tag = "12")]
    pub comp_ratio: i32,
    /// "stereo" | "mono" | "custom" | "mono-left" | "mono-right" | "karaoke" | "swap".
    #[prost(string, tag = "13")]
    pub channel_mode: ::prost::alloc::string::String,
    #[prost(int32, tag = "14")]
    pub stereo_width: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct State {
    #[prost(enumeration = "PlaybackState", tag = "1")]
    pub playback: i32,
    #[prost(message, optional, tag = "2")]
    pub station: ::core::option::Option<Station>,
    /// ICY "now playing" line, empty when unknown.
    #[prost(string, tag = "3")]
    pub title: ::prost::alloc::string::String,
    #[prost(float, tag = "4")]
    pub volume: f32,
    #[prost(bool, tag = "5")]
    pub muted: bool,
    #[prost(message, optional, tag = "6")]
    pub audio: ::core::option::Option<AudioSettings>,
    /// Bumped on every change so watchers can cheaply detect edits.
    #[prost(uint64, tag = "7")]
    pub version: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStateRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WatchStateRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PauseRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StopRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayPauseRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ToggleMuteRequest {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetVolumeRequest {
    #[prost(float, tag = "1")]
    pub volume: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoadStationRequest {
    #[prost(message, optional, tag = "1")]
    pub station: ::core::option::Option<Station>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAudioSettingsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAudioSettingsRequest {
    #[prost(message, optional, tag = "1")]
    pub audio: ::core::option::Option<AudioSettings>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AdjustDspRowRequest {
    #[prost(uint32, tag = "1")]
    pub row: u32,
    #[prost(int32, tag = "2")]
    pub dir: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FavoriteRequest {
    #[prost(message, optional, tag = "1")]
    pub station: ::core::option::Option<Station>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FavoriteResponse {
    #[prost(string, tag = "1")]
    pub uri: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListStationsRequest {
    #[prost(enumeration = "StationSource", tag = "1")]
    pub source: i32,
    /// Max results; 0 lets the server pick a sensible default.
    #[prost(uint32, tag = "2")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StationList {
    #[prost(message, repeated, tag = "1")]
    pub stations: ::prost::alloc::vec::Vec<Station>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlaybackState {
    Stopped = 0,
    Playing = 1,
    Paused = 2,
}
impl PlaybackState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Stopped => "PLAYBACK_STATE_STOPPED",
            Self::Playing => "PLAYBACK_STATE_PLAYING",
            Self::Paused => "PLAYBACK_STATE_PAUSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PLAYBACK_STATE_STOPPED" => Some(Self::Stopped),
            "PLAYBACK_STATE_PLAYING" => Some(Self::Playing),
            "PLAYBACK_STATE_PAUSED" => Some(Self::Paused),
            _ => None,
        }
    }
}
/// Which of the account's lists to browse.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StationSource {
    Favorites = 0,
    /// The account's own added stations ("Yours").
    Stations = 1,
    /// The account's recently-played.
    Recent = 2,
}
impl StationSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Favorites => "STATION_SOURCE_FAVORITES",
            Self::Stations => "STATION_SOURCE_STATIONS",
            Self::Recent => "STATION_SOURCE_RECENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATION_SOURCE_FAVORITES" => Some(Self::Favorites),
            "STATION_SOURCE_STATIONS" => Some(Self::Stations),
            "STATION_SOURCE_RECENT" => Some(Self::Recent),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod atradio_control_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Control a running `atradio` process (TUI or `--no-tui` daemon): drive
    /// playback, load a station, edit the Rockbox DSP/EQ chain, and favorite —
    /// plus a state stream for a remote now-playing bar. Served over a unix
    /// socket by default and, when configured, TCP (guarded by a bearer token).
    #[derive(Debug, Clone)]
    pub struct AtradioControlClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AtradioControlClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AtradioControlClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AtradioControlClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AtradioControlClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// One-shot snapshot of playback + audio settings.
        pub async fn get_state(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStateRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/GetState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "GetState"));
            self.inner.unary(req, path, codec).await
        }
        /// Snapshots streamed at ~2 Hz (playback state, now-playing, DSP).
        pub async fn watch_state(
            &mut self,
            request: impl tonic::IntoRequest<super::WatchStateRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::State>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/WatchState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "WatchState"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Transport.
        pub async fn play(
            &mut self,
            request: impl tonic::IntoRequest<super::PlayRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/Play",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "Play"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn pause(
            &mut self,
            request: impl tonic::IntoRequest<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/Pause",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "Pause"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop(
            &mut self,
            request: impl tonic::IntoRequest<super::StopRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/Stop",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "Stop"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn play_pause(
            &mut self,
            request: impl tonic::IntoRequest<super::PlayPauseRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/PlayPause",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "PlayPause"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn toggle_mute(
            &mut self,
            request: impl tonic::IntoRequest<super::ToggleMuteRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/ToggleMute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "ToggleMute"));
            self.inner.unary(req, path, codec).await
        }
        /// Absolute volume, 0.0..=1.0.
        pub async fn set_volume(
            &mut self,
            request: impl tonic::IntoRequest<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/SetVolume",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "SetVolume"));
            self.inner.unary(req, path, codec).await
        }
        /// Start playing a station (unwraps playlists / resolves the stream).
        pub async fn load_station(
            &mut self,
            request: impl tonic::IntoRequest<super::LoadStationRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/LoadStation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "LoadStation"));
            self.inner.unary(req, path, codec).await
        }
        /// Audio / DSP chain.
        pub async fn get_audio_settings(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAudioSettingsRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/GetAudioSettings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atradio.v1.AtradioControl", "GetAudioSettings"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Replace the whole DSP chain and apply it live.
        pub async fn set_audio_settings(
            &mut self,
            request: impl tonic::IntoRequest<super::SetAudioSettingsRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/SetAudioSettings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("atradio.v1.AtradioControl", "SetAudioSettings"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Nudge one DSP panel row, mirroring the TUI +/- keys (row order matches
        /// tui/dsp_rows.rs; dir is +1/-1).
        pub async fn adjust_dsp_row(
            &mut self,
            request: impl tonic::IntoRequest<super::AdjustDspRowRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/AdjustDspRow",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "AdjustDspRow"));
            self.inner.unary(req, path, codec).await
        }
        /// Favorite a station on the signed-in account. Returns the record URI.
        pub async fn favorite(
            &mut self,
            request: impl tonic::IntoRequest<super::FavoriteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FavoriteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/Favorite",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "Favorite"));
            self.inner.unary(req, path, codec).await
        }
        /// Browse the controlled instance's account lists (favorites / its own
        /// stations / recently-played), so a controller can play them remotely.
        /// Empty when the controlled instance isn't signed in.
        pub async fn list_stations(
            &mut self,
            request: impl tonic::IntoRequest<super::ListStationsRequest>,
        ) -> std::result::Result<tonic::Response<super::StationList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/atradio.v1.AtradioControl/ListStations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("atradio.v1.AtradioControl", "ListStations"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod atradio_control_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AtradioControlServer.
    #[async_trait]
    pub trait AtradioControl: std::marker::Send + std::marker::Sync + 'static {
        /// One-shot snapshot of playback + audio settings.
        async fn get_state(
            &self,
            request: tonic::Request<super::GetStateRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        /// Server streaming response type for the WatchState method.
        type WatchStateStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::State, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Snapshots streamed at ~2 Hz (playback state, now-playing, DSP).
        async fn watch_state(
            &self,
            request: tonic::Request<super::WatchStateRequest>,
        ) -> std::result::Result<tonic::Response<Self::WatchStateStream>, tonic::Status>;
        /// Transport.
        async fn play(
            &self,
            request: tonic::Request<super::PlayRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        async fn pause(
            &self,
            request: tonic::Request<super::PauseRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        async fn stop(
            &self,
            request: tonic::Request<super::StopRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        async fn play_pause(
            &self,
            request: tonic::Request<super::PlayPauseRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        async fn toggle_mute(
            &self,
            request: tonic::Request<super::ToggleMuteRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        /// Absolute volume, 0.0..=1.0.
        async fn set_volume(
            &self,
            request: tonic::Request<super::SetVolumeRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        /// Start playing a station (unwraps playlists / resolves the stream).
        async fn load_station(
            &self,
            request: tonic::Request<super::LoadStationRequest>,
        ) -> std::result::Result<tonic::Response<super::State>, tonic::Status>;
        /// Audio / DSP chain.
        async fn get_audio_settings(
            &self,
            request: tonic::Request<super::GetAudioSettingsRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status>;
        /// Replace the whole DSP chain and apply it live.
        async fn set_audio_settings(
            &self,
            request: tonic::Request<super::SetAudioSettingsRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status>;
        /// Nudge one DSP panel row, mirroring the TUI +/- keys (row order matches
        /// tui/dsp_rows.rs; dir is +1/-1).
        async fn adjust_dsp_row(
            &self,
            request: tonic::Request<super::AdjustDspRowRequest>,
        ) -> std::result::Result<tonic::Response<super::AudioSettings>, tonic::Status>;
        /// Favorite a station on the signed-in account. Returns the record URI.
        async fn favorite(
            &self,
            request: tonic::Request<super::FavoriteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FavoriteResponse>,
            tonic::Status,
        >;
        /// Browse the controlled instance's account lists (favorites / its own
        /// stations / recently-played), so a controller can play them remotely.
        /// Empty when the controlled instance isn't signed in.
        async fn list_stations(
            &self,
            request: tonic::Request<super::ListStationsRequest>,
        ) -> std::result::Result<tonic::Response<super::StationList>, tonic::Status>;
    }
    /// Control a running `atradio` process (TUI or `--no-tui` daemon): drive
    /// playback, load a station, edit the Rockbox DSP/EQ chain, and favorite —
    /// plus a state stream for a remote now-playing bar. Served over a unix
    /// socket by default and, when configured, TCP (guarded by a bearer token).
    #[derive(Debug)]
    pub struct AtradioControlServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AtradioControlServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AtradioControlServer<T>
    where
        T: AtradioControl,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/atradio.v1.AtradioControl/GetState" => {
                    #[allow(non_camel_case_types)]
                    struct GetStateSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::GetStateRequest>
                    for GetStateSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::get_state(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/WatchState" => {
                    #[allow(non_camel_case_types)]
                    struct WatchStateSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::ServerStreamingService<super::WatchStateRequest>
                    for WatchStateSvc<T> {
                        type Response = super::State;
                        type ResponseStream = T::WatchStateStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WatchStateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::watch_state(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = WatchStateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/Play" => {
                    #[allow(non_camel_case_types)]
                    struct PlaySvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::PlayRequest> for PlaySvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlayRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::play(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlaySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/Pause" => {
                    #[allow(non_camel_case_types)]
                    struct PauseSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::PauseRequest> for PauseSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PauseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::pause(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PauseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/Stop" => {
                    #[allow(non_camel_case_types)]
                    struct StopSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::StopRequest> for StopSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StopRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::stop(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/PlayPause" => {
                    #[allow(non_camel_case_types)]
                    struct PlayPauseSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::PlayPauseRequest>
                    for PlayPauseSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlayPauseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::play_pause(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlayPauseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/ToggleMute" => {
                    #[allow(non_camel_case_types)]
                    struct ToggleMuteSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::ToggleMuteRequest>
                    for ToggleMuteSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ToggleMuteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::toggle_mute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ToggleMuteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/SetVolume" => {
                    #[allow(non_camel_case_types)]
                    struct SetVolumeSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::SetVolumeRequest>
                    for SetVolumeSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetVolumeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::set_volume(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetVolumeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/LoadStation" => {
                    #[allow(non_camel_case_types)]
                    struct LoadStationSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::LoadStationRequest>
                    for LoadStationSvc<T> {
                        type Response = super::State;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoadStationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::load_station(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoadStationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/GetAudioSettings" => {
                    #[allow(non_camel_case_types)]
                    struct GetAudioSettingsSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::GetAudioSettingsRequest>
                    for GetAudioSettingsSvc<T> {
                        type Response = super::AudioSettings;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAudioSettingsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::get_audio_settings(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAudioSettingsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/SetAudioSettings" => {
                    #[allow(non_camel_case_types)]
                    struct SetAudioSettingsSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::SetAudioSettingsRequest>
                    for SetAudioSettingsSvc<T> {
                        type Response = super::AudioSettings;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetAudioSettingsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::set_audio_settings(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetAudioSettingsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/AdjustDspRow" => {
                    #[allow(non_camel_case_types)]
                    struct AdjustDspRowSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::AdjustDspRowRequest>
                    for AdjustDspRowSvc<T> {
                        type Response = super::AudioSettings;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AdjustDspRowRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::adjust_dsp_row(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AdjustDspRowSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/Favorite" => {
                    #[allow(non_camel_case_types)]
                    struct FavoriteSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::FavoriteRequest>
                    for FavoriteSvc<T> {
                        type Response = super::FavoriteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FavoriteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::favorite(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FavoriteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/atradio.v1.AtradioControl/ListStations" => {
                    #[allow(non_camel_case_types)]
                    struct ListStationsSvc<T: AtradioControl>(pub Arc<T>);
                    impl<
                        T: AtradioControl,
                    > tonic::server::UnaryService<super::ListStationsRequest>
                    for ListStationsSvc<T> {
                        type Response = super::StationList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListStationsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AtradioControl>::list_stations(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListStationsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AtradioControlServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "atradio.v1.AtradioControl";
    impl<T> tonic::server::NamedService for AtradioControlServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
