//! gRPC control API: a server (unix socket by default, optional TCP) that lets
//! another `atradio` instance drive this one, and a client used when this
//! instance is the controller. See `proto/atradio/v1/atradio.proto`.
//!
//! The tonic/prost-generated code + descriptor are committed (see `build.rs`)
//! so plain `cargo install atradio` builds without `protoc` installed.

#[path = ""]
pub mod api {
    /// Encoded FileDescriptorSet for gRPC server reflection (grpcurl etc.).
    pub const FILE_DESCRIPTOR_SET: &[u8] = include_bytes!("descriptor.bin");

    // The file is regenerated by tonic-build (prettyplease formatting), so
    // letting rustfmt/clippy touch it would fight codegen forever.
    #[allow(clippy::all, clippy::pedantic)]
    #[rustfmt::skip]
    #[path = "atradio.v1.rs"]
    pub mod v1;
}
