//! # atradio-sdk
//!
//! The official Rust SDK for [atradio.fm](https://atradio.fm) — a social
//! internet-radio platform built on the [AT Protocol](https://atproto.com),
//! built on top of [jacquard](https://crates.io/crates/jacquard).
//!
//! The design mirrors Bluesky's [`@atproto/api`](https://github.com/bluesky-social/atproto/tree/main/packages/api):
//! an [`AtradioAgent`] wraps a jacquard session and exposes both high-level
//! convenience verbs (`favorite`, `comment`, `set_play_status`) and a typed
//! namespace escape hatch. Reads go through the unauthenticated [`AppView`]
//! client.
//!
//! ```no_run
//! # async fn demo() -> atradio_sdk::Result<()> {
//! use atradio_sdk::AtradioAgent;
//!
//! let agent = AtradioAgent::builder()
//!     .session_store("~/.config/atradio/session.json")
//!     .build()?;
//! agent.login_password("alice.bsky.social", "app-password").await?;
//!
//! let recent = agent.appview().recent_stations(25).await?;
//! # let _ = recent;
//! # Ok(())
//! # }
//! ```
//!
//! The typed `fm.atradio.*` records live in [`fm_atradio`] (also re-exported as
//! [`lexicons`]); they are generated by `jacquard-lexgen` from
//! `packages/lexicons/lexicons/atradio/*.json`.

#![forbid(unsafe_code)]

// The generated lexicon code targets `no_std`-style paths (`alloc::…`).
extern crate alloc;

// --- generated from packages/lexicons/lexicons/atradio (see scripts/gen-lexicons.sh) ---
// These two modules live at the crate root because the generated code refers to
// them as `crate::fm_atradio` / `crate::builder_types` — keep the names so
// regenerated output drops in without edits.
#[allow(unused_imports, dead_code, clippy::all)]
pub mod builder_types;
#[allow(unused_imports, dead_code, clippy::all)]
pub mod fm_atradio;

/// The generated `fm.atradio.*` lexicon bindings, under the documented name.
pub use crate::fm_atradio as lexicons;

// --- hand-written SDK modules ---
pub mod agent;
pub mod appview;
pub mod auth;
pub mod error;
pub mod facets;
pub mod namespaces;

pub use agent::{AtradioAgent, AtradioAgentBuilder, StationDraft};
pub use appview::{AppView, StationInfo};
pub use auth::Profile;
pub use error::{Result, SdkError};

/// The default public AppView base URL.
pub const DEFAULT_APPVIEW: &str = "https://api.atradio.fm";
