// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.comment
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Did, AtUri, Cid, Datetime, UriValue};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::fm_atradio::StationInfo;
use crate::fm_atradio::comment;
/// An animated GIF embedded in a comment (e.g. from Giphy).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Gif<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alt: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    ///Smaller still/preview image URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview_url: Option<UriValue<S>>,
    ///Direct URL of the animated GIF/MP4.
    pub url: UriValue<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<i64>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// A user's comment on a radio station.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.comment",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Comment<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    ///Mentions of other actors, anchored to byte ranges in `text`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub facets: Option<Vec<comment::Mention<S>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gif: Option<comment::Gif<S>>,
    pub station: StationInfo<S>,
    ///The comment body (plain text).
    pub text: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CommentGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Comment<S>,
}

/// A mention of another actor within the comment text.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Mention<S: BosStr = DefaultStr> {
    ///Exclusive UTF-8 byte offset of the mention end.
    pub byte_end: i64,
    ///Inclusive UTF-8 byte offset of the mention start.
    pub byte_start: i64,
    pub did: Did<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

impl<S: BosStr> Comment<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, CommentRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

impl<S: BosStr> LexiconSchema for Gif<S> {
    fn nsid() -> &'static str {
        "fm.atradio.comment"
    }
    fn def_name() -> &'static str {
        "gif"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_comment()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.alt {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("alt"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.height {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("height"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.width {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("width"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct CommentRecord;
impl XrpcResp for CommentRecord {
    const NSID: &'static str = "fm.atradio.comment";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = CommentGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<CommentGetRecordOutput<S>> for Comment<S> {
    fn from(output: CommentGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Comment<S> {
    const NSID: &'static str = "fm.atradio.comment";
    type Record = CommentRecord;
}

impl Collection for CommentRecord {
    const NSID: &'static str = "fm.atradio.comment";
    type Record = CommentRecord;
}

impl<S: BosStr> LexiconSchema for Comment<S> {
    fn nsid() -> &'static str {
        "fm.atradio.comment"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_comment()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.text;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("text"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.text;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 300usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("text"),
                        max: 300usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for Mention<S> {
    fn nsid() -> &'static str {
        "fm.atradio.comment"
    }
    fn def_name() -> &'static str {
        "mention"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_comment()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.byte_end;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("byte_end"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.byte_start;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("byte_start"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod gif_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Url;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Url = Unset;
    }
    ///State transition - sets the `url` field to Set
    pub struct SetUrl<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUrl<St> {}
    impl<St: State> State for SetUrl<St> {
        type Url = Set<members::url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `url` field
        pub struct url(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GifBuilder<St: gif_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<i64>,
        Option<UriValue<S>>,
        Option<UriValue<S>>,
        Option<i64>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Gif<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GifBuilder<gif_state::Empty, DefaultStr> {
        GifBuilder::new()
    }
}

impl<S: BosStr> Gif<S> {
    /// Create a new builder for this type
    pub fn builder() -> GifBuilder<gif_state::Empty, S> {
        GifBuilder::builder()
    }
}

impl GifBuilder<gif_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GifBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GifBuilder<gif_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GifBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: gif_state::State, S: BosStr> GifBuilder<St, S> {
    /// Set the `alt` field (optional)
    pub fn alt(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `alt` field to an Option value (optional)
    pub fn maybe_alt(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: gif_state::State, S: BosStr> GifBuilder<St, S> {
    /// Set the `height` field (optional)
    pub fn height(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `height` field to an Option value (optional)
    pub fn maybe_height(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: gif_state::State, S: BosStr> GifBuilder<St, S> {
    /// Set the `previewUrl` field (optional)
    pub fn preview_url(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `previewUrl` field to an Option value (optional)
    pub fn maybe_preview_url(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GifBuilder<St, S>
where
    St: gif_state::State,
    St::Url: gif_state::IsUnset,
{
    /// Set the `url` field (required)
    pub fn url(
        mut self,
        value: impl Into<UriValue<S>>,
    ) -> GifBuilder<gif_state::SetUrl<St>, S> {
        self._fields.3 = Option::Some(value.into());
        GifBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: gif_state::State, S: BosStr> GifBuilder<St, S> {
    /// Set the `width` field (optional)
    pub fn width(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `width` field to an Option value (optional)
    pub fn maybe_width(mut self, value: Option<i64>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St, S: BosStr> GifBuilder<St, S>
where
    St: gif_state::State,
    St::Url: gif_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Gif<S> {
        Gif {
            alt: self._fields.0,
            height: self._fields.1,
            preview_url: self._fields.2,
            url: self._fields.3.unwrap(),
            width: self._fields.4,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Gif<S> {
        Gif {
            alt: self._fields.0,
            height: self._fields.1,
            preview_url: self._fields.2,
            url: self._fields.3.unwrap(),
            width: self._fields.4,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_comment() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.comment"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("gif"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "An animated GIF embedded in a comment (e.g. from Giphy).",
                        ),
                    ),
                    required: Some(vec![SmolStr::new_static("url")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("alt"),
                            LexObjectProperty::String(LexString {
                                max_length: Some(512usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("height"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("previewUrl"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static("Smaller still/preview image URL."),
                                ),
                                format: Some(LexStringFormat::Uri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("url"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static("Direct URL of the animated GIF/MP4."),
                                ),
                                format: Some(LexStringFormat::Uri),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("width"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static("A user's comment on a radio station."),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("station"), SmolStr::new_static("text"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("facets"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Mentions of other actors, anchored to byte ranges in `text`.",
                                        ),
                                    ),
                                    items: LexArrayItem::Ref(LexRef {
                                        r#ref: CowStr::new_static("fm.atradio.comment#mention"),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("gif"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("fm.atradio.comment#gif"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("station"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("fm.atradio.defs#stationInfo"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("text"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("The comment body (plain text)."),
                                    ),
                                    max_length: Some(3000usize),
                                    max_graphemes: Some(300usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("mention"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "A mention of another actor within the comment text.",
                        ),
                    ),
                    required: Some(
                        vec![
                            SmolStr::new_static("did"), SmolStr::new_static("byteStart"),
                            SmolStr::new_static("byteEnd")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("byteEnd"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("byteStart"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("did"),
                            LexObjectProperty::String(LexString {
                                format: Some(LexStringFormat::Did),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod comment_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Station;
        type Text;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Station = Unset;
        type Text = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Station = St::Station;
        type Text = St::Text;
    }
    ///State transition - sets the `station` field to Set
    pub struct SetStation<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStation<St> {}
    impl<St: State> State for SetStation<St> {
        type CreatedAt = St::CreatedAt;
        type Station = Set<members::station>;
        type Text = St::Text;
    }
    ///State transition - sets the `text` field to Set
    pub struct SetText<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetText<St> {}
    impl<St: State> State for SetText<St> {
        type CreatedAt = St::CreatedAt;
        type Station = St::Station;
        type Text = Set<members::text>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `station` field
        pub struct station(());
        ///Marker type for the `text` field
        pub struct text(());
    }
}

/// Builder for constructing an instance of this type.
pub struct CommentBuilder<St: comment_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<Vec<comment::Mention<S>>>,
        Option<comment::Gif<S>>,
        Option<StationInfo<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Comment<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> CommentBuilder<comment_state::Empty, DefaultStr> {
        CommentBuilder::new()
    }
}

impl<S: BosStr> Comment<S> {
    /// Create a new builder for this type
    pub fn builder() -> CommentBuilder<comment_state::Empty, S> {
        CommentBuilder::builder()
    }
}

impl CommentBuilder<comment_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        CommentBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> CommentBuilder<comment_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        CommentBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CommentBuilder<St, S>
where
    St: comment_state::State,
    St::CreatedAt: comment_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> CommentBuilder<comment_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: comment_state::State, S: BosStr> CommentBuilder<St, S> {
    /// Set the `facets` field (optional)
    pub fn facets(mut self, value: impl Into<Option<Vec<comment::Mention<S>>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `facets` field to an Option value (optional)
    pub fn maybe_facets(mut self, value: Option<Vec<comment::Mention<S>>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: comment_state::State, S: BosStr> CommentBuilder<St, S> {
    /// Set the `gif` field (optional)
    pub fn gif(mut self, value: impl Into<Option<comment::Gif<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `gif` field to an Option value (optional)
    pub fn maybe_gif(mut self, value: Option<comment::Gif<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> CommentBuilder<St, S>
where
    St: comment_state::State,
    St::Station: comment_state::IsUnset,
{
    /// Set the `station` field (required)
    pub fn station(
        mut self,
        value: impl Into<StationInfo<S>>,
    ) -> CommentBuilder<comment_state::SetStation<St>, S> {
        self._fields.3 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CommentBuilder<St, S>
where
    St: comment_state::State,
    St::Text: comment_state::IsUnset,
{
    /// Set the `text` field (required)
    pub fn text(
        mut self,
        value: impl Into<S>,
    ) -> CommentBuilder<comment_state::SetText<St>, S> {
        self._fields.4 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> CommentBuilder<St, S>
where
    St: comment_state::State,
    St::CreatedAt: comment_state::IsSet,
    St::Station: comment_state::IsSet,
    St::Text: comment_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Comment<S> {
        Comment {
            created_at: self._fields.0.unwrap(),
            facets: self._fields.1,
            gif: self._fields.2,
            station: self._fields.3.unwrap(),
            text: self._fields.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Comment<S> {
        Comment {
            created_at: self._fields.0.unwrap(),
            facets: self._fields.1,
            gif: self._fields.2,
            station: self._fields.3.unwrap(),
            text: self._fields.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod mention_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type ByteEnd;
        type ByteStart;
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type ByteEnd = Unset;
        type ByteStart = Unset;
        type Did = Unset;
    }
    ///State transition - sets the `byte_end` field to Set
    pub struct SetByteEnd<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetByteEnd<St> {}
    impl<St: State> State for SetByteEnd<St> {
        type ByteEnd = Set<members::byte_end>;
        type ByteStart = St::ByteStart;
        type Did = St::Did;
    }
    ///State transition - sets the `byte_start` field to Set
    pub struct SetByteStart<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetByteStart<St> {}
    impl<St: State> State for SetByteStart<St> {
        type ByteEnd = St::ByteEnd;
        type ByteStart = Set<members::byte_start>;
        type Did = St::Did;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type ByteEnd = St::ByteEnd;
        type ByteStart = St::ByteStart;
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `byte_end` field
        pub struct byte_end(());
        ///Marker type for the `byte_start` field
        pub struct byte_start(());
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct MentionBuilder<St: mention_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>, Option<Did<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Mention<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> MentionBuilder<mention_state::Empty, DefaultStr> {
        MentionBuilder::new()
    }
}

impl<S: BosStr> Mention<S> {
    /// Create a new builder for this type
    pub fn builder() -> MentionBuilder<mention_state::Empty, S> {
        MentionBuilder::builder()
    }
}

impl MentionBuilder<mention_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        MentionBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> MentionBuilder<mention_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        MentionBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MentionBuilder<St, S>
where
    St: mention_state::State,
    St::ByteEnd: mention_state::IsUnset,
{
    /// Set the `byteEnd` field (required)
    pub fn byte_end(
        mut self,
        value: impl Into<i64>,
    ) -> MentionBuilder<mention_state::SetByteEnd<St>, S> {
        self._fields.0 = Option::Some(value.into());
        MentionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MentionBuilder<St, S>
where
    St: mention_state::State,
    St::ByteStart: mention_state::IsUnset,
{
    /// Set the `byteStart` field (required)
    pub fn byte_start(
        mut self,
        value: impl Into<i64>,
    ) -> MentionBuilder<mention_state::SetByteStart<St>, S> {
        self._fields.1 = Option::Some(value.into());
        MentionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MentionBuilder<St, S>
where
    St: mention_state::State,
    St::Did: mention_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> MentionBuilder<mention_state::SetDid<St>, S> {
        self._fields.2 = Option::Some(value.into());
        MentionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MentionBuilder<St, S>
where
    St: mention_state::State,
    St::ByteEnd: mention_state::IsSet,
    St::ByteStart: mention_state::IsSet,
    St::Did: mention_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Mention<S> {
        Mention {
            byte_end: self._fields.0.unwrap(),
            byte_start: self._fields.1.unwrap(),
            did: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Mention<S> {
        Mention {
            byte_end: self._fields.0.unwrap(),
            byte_start: self._fields.1.unwrap(),
            did: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}