// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.favorite
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::fm_atradio::StationInfo;
/// A favorited radio station.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.favorite",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Favorite<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    pub station: StationInfo<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<Data<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct FavoriteGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Favorite<S>,
}

impl<S: BosStr> Favorite<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, FavoriteRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct FavoriteRecord;
impl XrpcResp for FavoriteRecord {
    const NSID: &'static str = "fm.atradio.favorite";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = FavoriteGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<FavoriteGetRecordOutput<S>> for Favorite<S> {
    fn from(output: FavoriteGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Favorite<S> {
    const NSID: &'static str = "fm.atradio.favorite";
    type Record = FavoriteRecord;
}

impl Collection for FavoriteRecord {
    const NSID: &'static str = "fm.atradio.favorite";
    type Record = FavoriteRecord;
}

impl<S: BosStr> LexiconSchema for Favorite<S> {
    fn nsid() -> &'static str {
        "fm.atradio.favorite"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_favorite()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

pub mod favorite_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Station;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Station = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Station = St::Station;
    }
    ///State transition - sets the `station` field to Set
    pub struct SetStation<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStation<St> {}
    impl<St: State> State for SetStation<St> {
        type CreatedAt = St::CreatedAt;
        type Station = Set<members::station>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `station` field
        pub struct station(());
    }
}

/// Builder for constructing an instance of this type.
pub struct FavoriteBuilder<St: favorite_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Datetime>, Option<StationInfo<S>>, Option<Data<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Favorite<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> FavoriteBuilder<favorite_state::Empty, DefaultStr> {
        FavoriteBuilder::new()
    }
}

impl<S: BosStr> Favorite<S> {
    /// Create a new builder for this type
    pub fn builder() -> FavoriteBuilder<favorite_state::Empty, S> {
        FavoriteBuilder::builder()
    }
}

impl FavoriteBuilder<favorite_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        FavoriteBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> FavoriteBuilder<favorite_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        FavoriteBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FavoriteBuilder<St, S>
where
    St: favorite_state::State,
    St::CreatedAt: favorite_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> FavoriteBuilder<favorite_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        FavoriteBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FavoriteBuilder<St, S>
where
    St: favorite_state::State,
    St::Station: favorite_state::IsUnset,
{
    /// Set the `station` field (required)
    pub fn station(
        mut self,
        value: impl Into<StationInfo<S>>,
    ) -> FavoriteBuilder<favorite_state::SetStation<St>, S> {
        self._fields.1 = Option::Some(value.into());
        FavoriteBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: favorite_state::State, S: BosStr> FavoriteBuilder<St, S> {
    /// Set the `subject` field (optional)
    pub fn subject(mut self, value: impl Into<Option<Data<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `subject` field to an Option value (optional)
    pub fn maybe_subject(mut self, value: Option<Data<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> FavoriteBuilder<St, S>
where
    St: favorite_state::State,
    St::CreatedAt: favorite_state::IsSet,
    St::Station: favorite_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Favorite<S> {
        Favorite {
            created_at: self._fields.0.unwrap(),
            station: self._fields.1.unwrap(),
            subject: self._fields.2,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Favorite<S> {
        Favorite {
            created_at: self._fields.0.unwrap(),
            station: self._fields.1.unwrap(),
            subject: self._fields.2,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_favorite() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.favorite"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(CowStr::new_static("A favorited radio station.")),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("station"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("station"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("fm.atradio.defs#stationInfo"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}