// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.getGlobalRecentlyPlayed
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::fm_atradio::PlayView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetGlobalRecentlyPlayed<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// (min: 1, max: 100)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetGlobalRecentlyPlayedOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub items: Vec<PlayView<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `fm.atradio.getGlobalRecentlyPlayed` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetGlobalRecentlyPlayedOutput<S>` for this endpoint.*/
pub struct GetGlobalRecentlyPlayedResponse;
impl jacquard_common::xrpc::XrpcResp for GetGlobalRecentlyPlayedResponse {
    const NSID: &'static str = "fm.atradio.getGlobalRecentlyPlayed";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetGlobalRecentlyPlayedOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetGlobalRecentlyPlayed<S> {
    const NSID: &'static str = "fm.atradio.getGlobalRecentlyPlayed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetGlobalRecentlyPlayedResponse;
}

/** Endpoint marker for the `fm.atradio.getGlobalRecentlyPlayed` query.

Path: `/xrpc/fm.atradio.getGlobalRecentlyPlayed`. The request payload type is `GetGlobalRecentlyPlayed<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetGlobalRecentlyPlayedRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetGlobalRecentlyPlayedRequest {
    const PATH: &'static str = "/xrpc/fm.atradio.getGlobalRecentlyPlayed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetGlobalRecentlyPlayed<S>;
    type Response = GetGlobalRecentlyPlayedResponse;
}

pub mod get_global_recently_played_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct GetGlobalRecentlyPlayedBuilder<
    St: get_global_recently_played_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetGlobalRecentlyPlayed<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetGlobalRecentlyPlayedBuilder<
        get_global_recently_played_state::Empty,
        DefaultStr,
    > {
        GetGlobalRecentlyPlayedBuilder::new()
    }
}

impl<S: BosStr> GetGlobalRecentlyPlayed<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetGlobalRecentlyPlayedBuilder<
        get_global_recently_played_state::Empty,
        S,
    > {
        GetGlobalRecentlyPlayedBuilder::builder()
    }
}

impl GetGlobalRecentlyPlayedBuilder<
    get_global_recently_played_state::Empty,
    DefaultStr,
> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetGlobalRecentlyPlayedBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<
    S: BosStr,
> GetGlobalRecentlyPlayedBuilder<get_global_recently_played_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetGlobalRecentlyPlayedBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<
    St: get_global_recently_played_state::State,
    S: BosStr,
> GetGlobalRecentlyPlayedBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<
    St: get_global_recently_played_state::State,
    S: BosStr,
> GetGlobalRecentlyPlayedBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> GetGlobalRecentlyPlayedBuilder<St, S>
where
    St: get_global_recently_played_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> GetGlobalRecentlyPlayed<S> {
        GetGlobalRecentlyPlayed {
            cursor: self._fields.0,
            limit: self._fields.1,
        }
    }
}