// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.getRecentlyPlayed
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::fm_atradio::PlayView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRecentlyPlayed<S: BosStr = DefaultStr> {
    pub actor: AtIdentifier<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// (min: 1, max: 100)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetRecentlyPlayedOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub items: Vec<PlayView<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `fm.atradio.getRecentlyPlayed` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetRecentlyPlayedOutput<S>` for this endpoint.*/
pub struct GetRecentlyPlayedResponse;
impl jacquard_common::xrpc::XrpcResp for GetRecentlyPlayedResponse {
    const NSID: &'static str = "fm.atradio.getRecentlyPlayed";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetRecentlyPlayedOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetRecentlyPlayed<S> {
    const NSID: &'static str = "fm.atradio.getRecentlyPlayed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetRecentlyPlayedResponse;
}

/** Endpoint marker for the `fm.atradio.getRecentlyPlayed` query.

Path: `/xrpc/fm.atradio.getRecentlyPlayed`. The request payload type is `GetRecentlyPlayed<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetRecentlyPlayedRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetRecentlyPlayedRequest {
    const PATH: &'static str = "/xrpc/fm.atradio.getRecentlyPlayed";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetRecentlyPlayed<S>;
    type Response = GetRecentlyPlayedResponse;
}

pub mod get_recently_played_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetActor<St> {}
    impl<St: State> State for SetActor<St> {
        type Actor = Set<members::actor>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetRecentlyPlayedBuilder<
    St: get_recently_played_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<AtIdentifier<S>>, Option<S>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl GetRecentlyPlayed<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetRecentlyPlayedBuilder<
        get_recently_played_state::Empty,
        DefaultStr,
    > {
        GetRecentlyPlayedBuilder::new()
    }
}

impl<S: BosStr> GetRecentlyPlayed<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetRecentlyPlayedBuilder<get_recently_played_state::Empty, S> {
        GetRecentlyPlayedBuilder::builder()
    }
}

impl GetRecentlyPlayedBuilder<get_recently_played_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetRecentlyPlayedBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetRecentlyPlayedBuilder<get_recently_played_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetRecentlyPlayedBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetRecentlyPlayedBuilder<St, S>
where
    St: get_recently_played_state::State,
    St::Actor: get_recently_played_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<AtIdentifier<S>>,
    ) -> GetRecentlyPlayedBuilder<get_recently_played_state::SetActor<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetRecentlyPlayedBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: get_recently_played_state::State, S: BosStr> GetRecentlyPlayedBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: get_recently_played_state::State, S: BosStr> GetRecentlyPlayedBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> GetRecentlyPlayedBuilder<St, S>
where
    St: get_recently_played_state::State,
    St::Actor: get_recently_played_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetRecentlyPlayed<S> {
        GetRecentlyPlayed {
            actor: self._fields.0.unwrap(),
            cursor: self._fields.1,
            limit: self._fields.2,
        }
    }
}