// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.reaction
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::fm_atradio::StationInfo;
/// An ephemeral emoji reaction to a radio station.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.reaction",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Reaction<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    ///A single emoji.
    pub emoji: S,
    pub station: StationInfo<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ReactionGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Reaction<S>,
}

impl<S: BosStr> Reaction<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, ReactionRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct ReactionRecord;
impl XrpcResp for ReactionRecord {
    const NSID: &'static str = "fm.atradio.reaction";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ReactionGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<ReactionGetRecordOutput<S>> for Reaction<S> {
    fn from(output: ReactionGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Reaction<S> {
    const NSID: &'static str = "fm.atradio.reaction";
    type Record = ReactionRecord;
}

impl Collection for ReactionRecord {
    const NSID: &'static str = "fm.atradio.reaction";
    type Record = ReactionRecord;
}

impl<S: BosStr> LexiconSchema for Reaction<S> {
    fn nsid() -> &'static str {
        "fm.atradio.reaction"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_reaction()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.emoji;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("emoji"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.emoji;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 4usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("emoji"),
                        max: 4usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

pub mod reaction_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Emoji;
        type Station;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Emoji = Unset;
        type Station = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Emoji = St::Emoji;
        type Station = St::Station;
    }
    ///State transition - sets the `emoji` field to Set
    pub struct SetEmoji<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetEmoji<St> {}
    impl<St: State> State for SetEmoji<St> {
        type CreatedAt = St::CreatedAt;
        type Emoji = Set<members::emoji>;
        type Station = St::Station;
    }
    ///State transition - sets the `station` field to Set
    pub struct SetStation<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStation<St> {}
    impl<St: State> State for SetStation<St> {
        type CreatedAt = St::CreatedAt;
        type Emoji = St::Emoji;
        type Station = Set<members::station>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `emoji` field
        pub struct emoji(());
        ///Marker type for the `station` field
        pub struct station(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ReactionBuilder<St: reaction_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Datetime>, Option<S>, Option<StationInfo<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Reaction<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ReactionBuilder<reaction_state::Empty, DefaultStr> {
        ReactionBuilder::new()
    }
}

impl<S: BosStr> Reaction<S> {
    /// Create a new builder for this type
    pub fn builder() -> ReactionBuilder<reaction_state::Empty, S> {
        ReactionBuilder::builder()
    }
}

impl ReactionBuilder<reaction_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ReactionBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ReactionBuilder<reaction_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ReactionBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ReactionBuilder<St, S>
where
    St: reaction_state::State,
    St::CreatedAt: reaction_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> ReactionBuilder<reaction_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ReactionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ReactionBuilder<St, S>
where
    St: reaction_state::State,
    St::Emoji: reaction_state::IsUnset,
{
    /// Set the `emoji` field (required)
    pub fn emoji(
        mut self,
        value: impl Into<S>,
    ) -> ReactionBuilder<reaction_state::SetEmoji<St>, S> {
        self._fields.1 = Option::Some(value.into());
        ReactionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ReactionBuilder<St, S>
where
    St: reaction_state::State,
    St::Station: reaction_state::IsUnset,
{
    /// Set the `station` field (required)
    pub fn station(
        mut self,
        value: impl Into<StationInfo<S>>,
    ) -> ReactionBuilder<reaction_state::SetStation<St>, S> {
        self._fields.2 = Option::Some(value.into());
        ReactionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ReactionBuilder<St, S>
where
    St: reaction_state::State,
    St::CreatedAt: reaction_state::IsSet,
    St::Emoji: reaction_state::IsSet,
    St::Station: reaction_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Reaction<S> {
        Reaction {
            created_at: self._fields.0.unwrap(),
            emoji: self._fields.1.unwrap(),
            station: self._fields.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Reaction<S> {
        Reaction {
            created_at: self._fields.0.unwrap(),
            emoji: self._fields.1.unwrap(),
            station: self._fields.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_reaction() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.reaction"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "An ephemeral emoji reaction to a radio station.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("station"),
                                SmolStr::new_static("emoji"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("emoji"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static("A single emoji.")),
                                    max_length: Some(32usize),
                                    max_graphemes: Some(4usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("station"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("fm.atradio.defs#stationInfo"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}