// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.atradio.station
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime, UriValue};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A user-defined radio station.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "fm.atradio.station",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Station<S: BosStr = DefaultStr> {
    pub created_at: Datetime,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub genre: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub homepage: Option<UriValue<S>>,
    ///Logo/artwork URL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logo: Option<UriValue<S>>,
    pub name: S,
    ///Direct, playable stream URL.
    pub stream_url: UriValue<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct StationGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Station<S>,
}

impl<S: BosStr> Station<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, StationRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct StationRecord;
impl XrpcResp for StationRecord {
    const NSID: &'static str = "fm.atradio.station";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = StationGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<StationGetRecordOutput<S>> for Station<S> {
    fn from(output: StationGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Station<S> {
    const NSID: &'static str = "fm.atradio.station";
    type Record = StationRecord;
}

impl Collection for StationRecord {
    const NSID: &'static str = "fm.atradio.station";
    type Record = StationRecord;
}

impl<S: BosStr> LexiconSchema for Station<S> {
    fn nsid() -> &'static str {
        "fm.atradio.station"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fm_atradio_station()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.description {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 2000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("description"),
                    max: 2000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.genre {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("genre"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("name"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("name"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod station_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Name;
        type StreamUrl;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Name = Unset;
        type StreamUrl = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Name = St::Name;
        type StreamUrl = St::StreamUrl;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetName<St> {}
    impl<St: State> State for SetName<St> {
        type CreatedAt = St::CreatedAt;
        type Name = Set<members::name>;
        type StreamUrl = St::StreamUrl;
    }
    ///State transition - sets the `stream_url` field to Set
    pub struct SetStreamUrl<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStreamUrl<St> {}
    impl<St: State> State for SetStreamUrl<St> {
        type CreatedAt = St::CreatedAt;
        type Name = St::Name;
        type StreamUrl = Set<members::stream_url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `stream_url` field
        pub struct stream_url(());
    }
}

/// Builder for constructing an instance of this type.
pub struct StationBuilder<St: station_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Datetime>,
        Option<S>,
        Option<S>,
        Option<UriValue<S>>,
        Option<UriValue<S>>,
        Option<S>,
        Option<UriValue<S>>,
        Option<Vec<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Station<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> StationBuilder<station_state::Empty, DefaultStr> {
        StationBuilder::new()
    }
}

impl<S: BosStr> Station<S> {
    /// Create a new builder for this type
    pub fn builder() -> StationBuilder<station_state::Empty, S> {
        StationBuilder::builder()
    }
}

impl StationBuilder<station_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        StationBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> StationBuilder<station_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        StationBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> StationBuilder<St, S>
where
    St: station_state::State,
    St::CreatedAt: station_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> StationBuilder<station_state::SetCreatedAt<St>, S> {
        self._fields.0 = Option::Some(value.into());
        StationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: station_state::State, S: BosStr> StationBuilder<St, S> {
    /// Set the `description` field (optional)
    pub fn description(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: station_state::State, S: BosStr> StationBuilder<St, S> {
    /// Set the `genre` field (optional)
    pub fn genre(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `genre` field to an Option value (optional)
    pub fn maybe_genre(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: station_state::State, S: BosStr> StationBuilder<St, S> {
    /// Set the `homepage` field (optional)
    pub fn homepage(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `homepage` field to an Option value (optional)
    pub fn maybe_homepage(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: station_state::State, S: BosStr> StationBuilder<St, S> {
    /// Set the `logo` field (optional)
    pub fn logo(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `logo` field to an Option value (optional)
    pub fn maybe_logo(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St, S: BosStr> StationBuilder<St, S>
where
    St: station_state::State,
    St::Name: station_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(mut self, value: impl Into<S>) -> StationBuilder<station_state::SetName<St>, S> {
        self._fields.5 = Option::Some(value.into());
        StationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> StationBuilder<St, S>
where
    St: station_state::State,
    St::StreamUrl: station_state::IsUnset,
{
    /// Set the `streamUrl` field (required)
    pub fn stream_url(
        mut self,
        value: impl Into<UriValue<S>>,
    ) -> StationBuilder<station_state::SetStreamUrl<St>, S> {
        self._fields.6 = Option::Some(value.into());
        StationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: station_state::State, S: BosStr> StationBuilder<St, S> {
    /// Set the `tags` field (optional)
    pub fn tags(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St, S: BosStr> StationBuilder<St, S>
where
    St: station_state::State,
    St::CreatedAt: station_state::IsSet,
    St::Name: station_state::IsSet,
    St::StreamUrl: station_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Station<S> {
        Station {
            created_at: self._fields.0.unwrap(),
            description: self._fields.1,
            genre: self._fields.2,
            homepage: self._fields.3,
            logo: self._fields.4,
            name: self._fields.5.unwrap(),
            stream_url: self._fields.6.unwrap(),
            tags: self._fields.7,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Station<S> {
        Station {
            created_at: self._fields.0.unwrap(),
            description: self._fields.1,
            genre: self._fields.2,
            homepage: self._fields.3,
            logo: self._fields.4,
            name: self._fields.5.unwrap(),
            stream_url: self._fields.6.unwrap(),
            tags: self._fields.7,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fm_atradio_station() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fm.atradio.station"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(CowStr::new_static("A user-defined radio station.")),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(vec![
                            SmolStr::new_static("name"),
                            SmolStr::new_static("streamUrl"),
                            SmolStr::new_static("createdAt"),
                        ]),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    max_length: Some(2000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("genre"),
                                LexObjectProperty::String(LexString {
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("homepage"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("logo"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static("Logo/artwork URL.")),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("name"),
                                LexObjectProperty::String(LexString {
                                    min_length: Some(1usize),
                                    max_length: Some(512usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("streamUrl"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static(
                                        "Direct, playable stream URL.",
                                    )),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("tags"),
                                LexObjectProperty::Array(LexArray {
                                    items: LexArrayItem::String(LexString {
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
